"""baseline schema

Revision ID: 42b3db3ee8f8
Revises:
Create Date: 2026-08-26 17:03:03.785897

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42b3db3ee8f8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Enum types created implicitly by the tables below.
ENUM_TYPES = ("moduleenum", "questiontypeenum", "assessmentstatusenum")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('module', sa.Enum('RIASEC', 'BIG5', 'COGNITIVE', 'SJT', name='moduleenum'), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('text_ru', sa.String(), nullable=True),
    sa.Column('text_kz', sa.String(), nullable=True),
    sa.Column('text_en', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('scale', 'choice', name='questiontypeenum'), nullable=False),
    sa.Column('is_reverse', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_code'), 'questions', ['code'], unique=True)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('test_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riasec_limit', sa.Integer(), nullable=False),
    sa.Column('big5_limit', sa.Integer(), nullable=False),
    sa.Column('sjt_limit', sa.Integer(), nullable=False),
    sa.Column('cognitive_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_configs_id'), 'test_configs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('started', 'completed', name='assessmentstatusenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('raw_scores', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_sessions_id'), 'assessment_sessions', ['id'], unique=False)
    op.create_table('user_profile_aggregates',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tests_count', sa.Integer(), nullable=False),
    sa.Column('aggregated_scores_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('assessment_run_snapshots',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('versions_json', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_assessment_run_snapshots_input_hash'), 'assessment_run_snapshots', ['input_hash'], unique=False)
    op.create_index(op.f('ix_assessment_run_snapshots_user_id'), 'assessment_run_snapshots', ['user_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('evidence_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('locator_json', sa.JSON(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_items_run_id'), 'evidence_items', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_user_id'), 'evidence_items', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('selected_rec_ids_json', sa.JSON(), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('versions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_plans_run_id'), 'plans', ['run_id'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('reaction_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['assessment_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_responses_id'), 'user_responses', ['id'], unique=False)
    op.create_table('plan_task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'task_id', name='uq_plan_task_status_plan_task')
    )
    op.create_index(op.f('ix_plan_task_status_id'), 'plan_task_status', ['id'], unique=False)
    op.create_index(op.f('ix_plan_task_status_plan_id'), 'plan_task_status', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_task_status_plan_id'), table_name='plan_task_status')
    op.drop_index(op.f('ix_plan_task_status_id'), table_name='plan_task_status')
    op.drop_table('plan_task_status')
    op.drop_index(op.f('ix_user_responses_id'), table_name='user_responses')
    op.drop_table('user_responses')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_run_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_evidence_items_user_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_run_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_assessment_run_snapshots_user_id'), table_name='assessment_run_snapshots')
    op.drop_index(op.f('ix_assessment_run_snapshots_input_hash'), table_name='assessment_run_snapshots')
    op.drop_table('assessment_run_snapshots')
    op.drop_table('user_profile_aggregates')
    op.drop_index(op.f('ix_assessment_sessions_id'), table_name='assessment_sessions')
    op.drop_table('assessment_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_configs_id'), table_name='test_configs')
    op.drop_table('test_configs')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_code'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###

    # Dropping a table does not drop the enum type it used, and a later
    # upgrade would then fail on "type already exists".
    for enum_name in ENUM_TYPES:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
